apiVersion: v1
kind: Service
metadata:
  name: backend-user-svc
  labels:
    service: udagram-api-user
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: udagram-api-user
  type: ClusterIP