apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: backend-feed
        image: gauravsinghaec/udagram-api-feed:v1
        envFrom:
          - secretRef:
              name: udagram-secret
          - configMapRef:
              name: udagram-config-map
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 200Mi