apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: frontend
        image: gauravsinghaec/udagram-frontend:v1
        ports:
        - containerPort: 80