apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    service: udagram-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    service: udagram-frontend
  type: ClusterIP