apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
  labels:
    service: udagram-reverseproxy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: udagram-reverseproxy
  type: ClusterIP